"""sys prompt

Revision ID: 0121d3810d38
Revises: 8b5cfe51860d
Create Date: 2024-04-14 22:39:53.974073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0121d3810d38'
down_revision = '8b5cfe51860d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cwd_system_prompt', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.drop_column('cwd_system_prompt')

    # ### end Alembic commands ###
