"""more key change

Revision ID: 09b42e7fb518
Revises: 1d314bf33961
Create Date: 2024-01-16 21:06:42.757020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09b42e7fb518"
down_revision = "1d314bf33961"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("users_ibfk_1", type_="foreignkey")
        batch_op.create_foreign_key(None, "user_api_keys", ["selected_api_key_id"], ["id"])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "users_ibfk_1", "user_api_keys", ["selected_api_key_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###
