"""Add roles and user-role relationship

Revision ID: 0a8a3fab7398
Revises: 471944e295ad
Create Date: 2024-01-13 09:25:41.289824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a8a3fab7398'
down_revision = '471944e295ad'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('tts_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_format', sa.Enum('mp3', 'opus', 'aac', 'flac'), nullable=False))
        batch_op.drop_column('output')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('tts_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output', mysql.ENUM('mp3', 'opus', 'aac', 'flac'), nullable=False))
        batch_op.drop_column('response_format')


    # ### end Alembic commands ###
