"""default key name, convo title

Revision ID: 170ecc80450f
Revises: fe0cc8b6d5d1
Create Date: 2023-12-12 13:39:39.118248

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '170ecc80450f'
down_revision = 'fe0cc8b6d5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True,
                                      default='New Conversation'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_api_keys', ['selected_api_key_id'],
                                    ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_ibfk_1', 'user_api_keys',
                                    ['selected_api_key_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
