"""remove unique requirement for key

Revision ID: 1d314bf33961
Revises: 922201d52caa
Create Date: 2024-01-16 18:47:06.697760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d314bf33961'
down_revision = '922201d52caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index('api_key_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index('api_key_token', ['api_key_token'], unique=False)

    # ### end Alembic commands ###
