"""rid of url, use uuid

Revision ID: 1de923d11752
Revises: da5f9e02fdd0
Create Date: 2023-11-24 00:12:10.357478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1de923d11752'
down_revision = 'da5f9e02fdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid'])
        batch_op.drop_column('temp_file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_file_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
