"""db additions, removed unused tables

Revision ID: 25c3131b8242
Revises: 5f8b9cbbd192
Create Date: 2023-12-20 12:44:26.587840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25c3131b8242'
down_revision = '5f8b9cbbd192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_table('audio_files')
    op.drop_table('speeches')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_image_gen', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('usage_chat', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('usage_embedding', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('voice_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('voice_quality', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vision_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('knowledge_query_mode', sa.Boolean(), nullable=True))
        batch_op.drop_column('show_timestamps')

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_voice', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_vision', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_image_gen', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('usage_chat', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('usage_embedding', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_column('usage_embedding')
        batch_op.drop_column('usage_chat')
        batch_op.drop_column('usage_image_gen')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_vision')
        batch_op.drop_column('is_voice')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('pages')

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_column('pages')

    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_timestamps', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('knowledge_query_mode')
        batch_op.drop_column('vision_mode')
        batch_op.drop_column('voice_quality')
        batch_op.drop_column('voice_model')
        batch_op.drop_column('voice_mode')

    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_column('usage_embedding')
        batch_op.drop_column('usage_chat')
        batch_op.drop_column('usage_image_gen')

    op.create_table('speeches',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('voice', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('audio_data', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='speeches_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('audio_files',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('transcription', mysql.TEXT(), nullable=True),
    sa.Column('language', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audio_files_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('translations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_text', mysql.TEXT(), nullable=False),
    sa.Column('translated_text', mysql.TEXT(), nullable=False),
    sa.Column('source_language', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('target_language', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='translations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
