"""audio changes

Revision ID: 26241a5d40ce
Revises: ace2821112e1
Create Date: 2024-01-14 19:52:39.528745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26241a5d40ce'
down_revision = 'ace2821112e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_job_segments')
    op.drop_table('audio_jobs')
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['chunk_id'])

    with op.batch_alter_table('tier_limit', schema=None) as batch_op:
        batch_op.drop_column('max_image_storage')

    with op.batch_alter_table('transcription_job_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_content', sa.Text(), nullable=False))
        batch_op.create_index(batch_op.f('ix_transcription_job_segments_transcription_job_id'), ['transcription_job_id'], unique=False)
        batch_op.drop_column('output_file_path')
        batch_op.drop_column('input_file_path')

    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('finished', sa.Boolean(), nullable=False))
        batch_op.alter_column('prompt',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('final_output_path')

    with op.batch_alter_table('translation_job_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_content', sa.Text(), nullable=False))
        batch_op.create_index(batch_op.f('ix_translation_job_segments_translation_job_id'), ['translation_job_id'], unique=False)
        batch_op.drop_column('output_file_path')
        batch_op.drop_column('input_file_path')

    with op.batch_alter_table('translation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('finished', sa.Boolean(), nullable=False))
        batch_op.alter_column('prompt',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('final_output_path')

    with op.batch_alter_table('tts_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('final_output_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tts_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_output_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('output_filename')

    with op.batch_alter_table('translation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_output_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('prompt',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('finished')
        batch_op.drop_column('input_filename')

    with op.batch_alter_table('translation_job_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_file_path', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('output_file_path', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('output_content')

    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_output_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('prompt',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('finished')
        batch_op.drop_column('input_filename')

    with op.batch_alter_table('transcription_job_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_file_path', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('output_file_path', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_transcription_job_segments_transcription_job_id'))
        batch_op.drop_column('output_content')

    with op.batch_alter_table('tier_limit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_image_storage', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('audio_jobs',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('type', mysql.ENUM('tts', 'transcription', 'translation'), nullable=False),
    sa.Column('model', mysql.ENUM('tts-1', 'tts-1-hd', 'whisper-1'), nullable=False),
    sa.Column('voice', mysql.ENUM('alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'), nullable=True),
    sa.Column('response_format', mysql.ENUM('mp3', 'opus', 'aac', 'flac', 'json', 'text', 'srt', 'verbose_json', 'vtt'), nullable=False),
    sa.Column('speed', mysql.FLOAT(), nullable=True),
    sa.Column('language', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('temperature', mysql.FLOAT(), nullable=True),
    sa.Column('final_output_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audio_jobs_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('audio_job_segments',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('audio_job_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('input_file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('output_file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('job_index', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['audio_job_id'], ['audio_jobs.id'], name='audio_job_segments_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
