"""expanded roles

Revision ID: 35315f420793
Revises: bc942ace2370
Create Date: 2024-01-30 17:07:10.813291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35315f420793"
down_revision = "bc942ace2370"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tier_limit", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_chat_messages", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("embed_dimensions", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("tier_limit", schema=None) as batch_op:
        batch_op.drop_column("embed_dimensions")
        batch_op.drop_column("max_chat_messages")

    # ### end Alembic commands ###
