"""pages to blob

Revision ID: 4928392f9a10
Revises: ae4d18d82eee
Create Date: 2023-12-21 09:35:47.520672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4928392f9a10'
down_revision = 'ae4d18d82eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=mysql.INTEGER(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=sa.BLOB(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
