"""expanded embeddings table

Revision ID: 4ea2f39ae287
Revises: f81005ce6336
Create Date: 2023-11-24 18:26:59.199970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ea2f39ae287'
down_revision = 'f81005ce6336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_id', sa.Integer(), nullable=True))
        batch_op.alter_column('embedding',
               existing_type=mysql.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'document_chunks', ['chunk_id'], ['id'])
        batch_op.drop_column('chunk_index')
        batch_op.drop_column('document')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('chunk_index', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('embedding',
               existing_type=sa.LargeBinary(),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('chunk_id')

    # ### end Alembic commands ###
