"""sys prompt tokens

Revision ID: 535891f642b9
Revises: 0121d3810d38
Create Date: 2024-07-16 13:20:22.973042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '535891f642b9'
down_revision = '0121d3810d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.alter_column('cwd_system_prompt',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=4096),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.alter_column('cwd_system_prompt',
               existing_type=sa.String(length=4096),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###
