"""cascade delete on many tables that have fks with user id

Revision ID: 57e211382e85
Revises: 447d3301e5e4
Create Date: 2023-12-10 00:44:15.674791

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '57e211382e85'
down_revision = '447d3301e5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_constraint('api_usage_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'],
                                    ondelete='CASCADE')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('conversations_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'],
                                    ondelete='CASCADE')

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_constraint('document_chunks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'],
                                    ondelete='CASCADE')

    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint('document_embeddings_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('document_embeddings_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'],
                                    ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'document_chunks', ['chunk_id'], ['id'],
                                    ondelete='CASCADE')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('documents_ibfk_1', type_='foreignkey')
        batch_op.drop_index('fk_documents_user')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'],
                                    ondelete='CASCADE')

    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_constraint('generated_images_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'],
                                    ondelete='CASCADE')

    with op.batch_alter_table('speeches', schema=None) as batch_op:
        batch_op.drop_constraint('speeches_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'],
                                    ondelete='CASCADE')

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_constraint('translations_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'],
                                    ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('translations_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('speeches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('speeches_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('generated_images_ibfk_1', 'users', ['user_id'],
                                    ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('documents_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.create_index('fk_documents_user', ['user_id'], unique=False)

    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_embeddings_ibfk_2', 'document_chunks',
                                    ['chunk_id'], ['id'])
        batch_op.create_foreign_key('document_embeddings_ibfk_1', 'users', ['user_id'],
                                    ['id'])

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_chunks_ibfk_1', 'documents',
                                    ['document_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('conversations_ibfk_1', 'users', ['user_id'],
                                    ['id'])

    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('api_usage_ibfk_1', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
