"""interrupt boolean in convo table

Revision ID: 5f8b9cbbd192
Revises: b3ed5fd1a42f
Create Date: 2023-12-19 14:05:37.956856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8b9cbbd192'
down_revision = 'b3ed5fd1a42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_interrupted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('is_interrupted')

    # ### end Alembic commands ###
