"""nullable, default0

Revision ID: 6c27687a0f3e
Revises: 89de920e7162
Create Date: 2023-12-20 18:13:02.649598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c27687a0f3e'
down_revision = '89de920e7162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.alter_column('usage_image_gen',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('usage_chat',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('usage_embedding',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('usage_audio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.alter_column('usage_image_gen',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('usage_chat',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('usage_embedding',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('usage_audio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.alter_column('usage_audio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('usage_embedding',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('usage_chat',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('usage_image_gen',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.alter_column('usage_audio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('usage_embedding',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('usage_chat',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('usage_image_gen',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###
