"""added filename to audio jobs

Revision ID: 759d61cc626a
Revises: 378f0586c3f1
Create Date: 2024-04-09 12:21:37.349322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759d61cc626a'
down_revision = '378f0586c3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))

    with op.batch_alter_table('translation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_jobs', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
