"""selected boolean to docs

Revision ID: 798208448c70
Revises: 327aa49f6b19
Create Date: 2023-12-24 00:06:14.876401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798208448c70'
down_revision = '327aa49f6b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('selected')

    # ### end Alembic commands ###
