"""removed unused columns from apiusage

Revision ID: 89de920e7162
Revises: 91fbc53eaae0
Create Date: 2023-12-20 15:51:04.360061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89de920e7162'
down_revision = '91fbc53eaae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('request_payload')
        batch_op.drop_column('endpoint')
        batch_op.drop_column('response_payload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_payload', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('endpoint', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('request_payload', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    # ### end Alembic commands ###
