"""changed knowledge tokens to top_k, added threshold

Revision ID: 8b5cfe51860d
Revises: 772940d8d47a
Create Date: 2024-04-14 20:10:11.439371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b5cfe51860d'
down_revision = '772940d8d47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_k', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('threshold', sa.Float(), nullable=True))
        batch_op.drop_column('knowledge_context_tokens')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_context_tokens', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('threshold')
        batch_op.drop_column('top_k')

    # ### end Alembic commands ###
