"""page string

Revision ID: 8d5d90ff4233
Revises: 535891f642b9
Create Date: 2024-07-20 15:34:10.913783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d5d90ff4233'
down_revision = '535891f642b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###
