"""audio usage to apiusage

Revision ID: 91fbc53eaae0
Revises: 25c3131b8242
Create Date: 2023-12-20 12:50:28.136671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fbc53eaae0'
down_revision = '25c3131b8242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_audio', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_audio', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_column('usage_audio')

    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_column('usage_audio')

    # ### end Alembic commands ###
