"""deleted download flags

Revision ID: 922201d52caa
Revises: 6d23368f9407
Create Date: 2024-01-16 16:27:46.615008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '922201d52caa'
down_revision = '6d23368f9407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.drop_column('download_timestamp')
        batch_op.drop_column('download_url')

    with op.batch_alter_table('translation_jobs', schema=None) as batch_op:
        batch_op.drop_column('download_timestamp')
        batch_op.drop_column('download_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('download_timestamp', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('download_timestamp', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
