"""made specific columns indices for faster querying

Revision ID: a74e6d0ac15d
Revises: cff48f55267b
Create Date: 2024-01-03 00:36:06.753266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74e6d0ac15d'
down_revision = 'cff48f55267b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.drop_index('user_id')
        batch_op.create_index(batch_op.f('ix_chat_preferences_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_chunk_index'), ['chunk_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('message_chunk_association', schema=None) as batch_op:
        batch_op.drop_index('ix_message_chunk_association_similarity_rank')

    with op.batch_alter_table('message_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_images_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_images_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_keys_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_keys_user_id'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    with op.batch_alter_table('message_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_images_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_images_message_id'))

    with op.batch_alter_table('message_chunk_association', schema=None) as batch_op:
        batch_op.create_index('ix_message_chunk_association_similarity_rank', ['similarity_rank'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_chunk_index'))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))

    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_preferences_user_id'))
        batch_op.create_index('user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
