"""5 deci places

Revision ID: ae4d18d82eee
Revises: 6c27687a0f3e
Create Date: 2023-12-20 18:28:18.953675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae4d18d82eee'
down_revision = '6c27687a0f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.alter_column('usage_image_gen',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=5),
               existing_nullable=False)
        batch_op.alter_column('usage_chat',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=5),
               existing_nullable=False)
        batch_op.alter_column('usage_embedding',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=5),
               existing_nullable=False)
        batch_op.alter_column('usage_audio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=5),
               existing_nullable=False)

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.alter_column('usage_image_gen',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=5),
               existing_nullable=False)
        batch_op.alter_column('usage_chat',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=5),
               existing_nullable=False)
        batch_op.alter_column('usage_embedding',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=5),
               existing_nullable=False)
        batch_op.alter_column('usage_audio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.alter_column('usage_audio',
               existing_type=sa.Numeric(precision=10, scale=5),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('usage_embedding',
               existing_type=sa.Numeric(precision=10, scale=5),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('usage_chat',
               existing_type=sa.Numeric(precision=10, scale=5),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('usage_image_gen',
               existing_type=sa.Numeric(precision=10, scale=5),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.alter_column('usage_audio',
               existing_type=sa.Numeric(precision=10, scale=5),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('usage_embedding',
               existing_type=sa.Numeric(precision=10, scale=5),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('usage_chat',
               existing_type=sa.Numeric(precision=10, scale=5),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('usage_image_gen',
               existing_type=sa.Numeric(precision=10, scale=5),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
