"""last checked column in convo tb

Revision ID: b3ed5fd1a42f
Revises: 9e85d5a48ec0
Create Date: 2023-12-17 23:37:06.026256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ed5fd1a42f'
down_revision = '9e85d5a48ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('last_checked_time')

    # ### end Alembic commands ###
