"""tokens for docs

Revision ID: b8881d16f555
Revises: e9d45ede83a2
Create Date: 2023-11-24 19:59:48.241411

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b8881d16f555'
down_revision = 'e9d45ede83a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'),
                      nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
