"""tasks

Revision ID: bc942ace2370
Revises: c4f1a0ce53f5
Create Date: 2024-01-18 15:31:49.684559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc942ace2370'
down_revision = 'c4f1a0ce53f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_images', schema=None) as batch_op:
        batch_op.drop_index('uuid')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('input_params')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_params', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('message_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(length=255), nullable=False))
        batch_op.create_index('uuid', ['uuid'], unique=False)

    # ### end Alembic commands ###
