"""knowledge context tokens

Revision ID: cff48f55267b
Revises: 798208448c70
Create Date: 2023-12-24 00:40:05.065123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cff48f55267b'
down_revision = '798208448c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_context_tokens', sa.Integer(), nullable=True))
        batch_op.drop_column('vision_mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vision_mode', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('knowledge_context_tokens')

    # ### end Alembic commands ###
