"""save img download path

Revision ID: da5f9e02fdd0
Revises: 9dc9ae99d316
Create Date: 2023-11-23 07:55:54.333440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5f9e02fdd0'
down_revision = '9dc9ae99d316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_column('temp_file_path')

    # ### end Alembic commands ###
