"""pages to str

Revision ID: dbb5f9b9f5a1
Revises: 4928392f9a10
Create Date: 2023-12-21 09:56:42.041173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb5f9b9f5a1'
down_revision = '4928392f9a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=sa.BLOB(),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=sa.String(length=25),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
