"""message imgs table

Revision ID: e25bf237dc17
Revises: dbb5f9b9f5a1
Create Date: 2023-12-22 17:06:01.652933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e25bf237dc17'
down_revision = 'dbb5f9b9f5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.drop_column('voice_quality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('voice_quality', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
