"""foreign key cascade on delete

Revision ID: e3cb7a495239
Revises: b8881d16f555
Create Date: 2023-12-03 02:18:45.794771

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e3cb7a495239'
down_revision = 'b8881d16f555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_constraint('document_chunks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'],
                                    ondelete='CASCADE')

    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint('document_embeddings_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'document_chunks', ['chunk_id'], ['id'],
                                    ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_embeddings_ibfk_2', 'document_chunks',
                                    ['chunk_id'], ['id'])

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('document_chunks_ibfk_1', 'documents',
                                    ['document_id'], ['id'])

    # ### end Alembic commands ###
