"""add boolean stream

Revision ID: e7c184986a70
Revises: f5dac3121ded
Create Date: 2023-12-04 02:10:30.018497

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e7c184986a70'
down_revision = 'f5dac3121ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stream', sa.Boolean(), nullable=True))


def downgrade():
    with op.batch_alter_table('chat_preferences', schema=None) as batch_op:
        batch_op.drop_column('stream')

    # ### end Alembic commands ###
