"""cascade delete on many tables that have fks with user id

Revision ID: fe0cc8b6d5d1
Revises: 57e211382e85
Create Date: 2023-12-10 00:48:35.609168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0cc8b6d5d1'
down_revision = '57e211382e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_constraint('user_api_keys_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_api_keys_ibfk_1', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
